server:
  port: 7000

logging:
  file: d:\\logs\\stdout.log
  level:  DEBUG


debug: true


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blue?useUnicode=true&amp;characterEncoding=utf8mb4
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

#单节点方式
  redis:
    url: 127.0.0.1
    database: 0
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
