server:
  port: 7000

logging:
  file: d:\\logs\\stdout.log
  level:  DEBUG

debug: true


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blue?useUnicode=true&amp;characterEncoding=utf8mb4
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

