
server:
  port: 8081


eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://lib:test@localhost:8080/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}${server.port}

spring:
  application:
    name: appname-libin

