
server:
  port: 8080
logging:
  level:
    root:INFO
    com.libin:INFO

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://lib:test@localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

spring:
  application:
    name: appname-libin

